#!/bin/bash

if mktemp --directory >/dev/null 2>&1; then
    TEMP="$(mktemp --directory)"
else
    TEMP="$(mktemp -d)"
fi
trap 'rm -rf -- "$TEMP"' EXIT

while IFS="" read -r FILE
do
    mkdir -p -- "$TEMP/$(dirname $FILE)"
    git cat-file -p ":$FILE" > "$TEMP/$FILE"
done < <(git diff --name-only --cached --diff-filter=d)

REPO=$PWD
cd "$TEMP"

# -----------------------------------------------------------------------------
if [[ -x "$REPO/.venv/bin/python" ]]; then
    "$REPO/.venv/bin/python" -m flake8 --config "$REPO/setup.cfg" .
elif command -v py >/dev/null 2>&1; then
    py 10 -s -m flake8 --config "$REPO/setup.cfg" .
elif command -v python3 >/dev/null 2>&1; then
    python3 -m flake8 --config "$REPO/setup.cfg" .
else
    python -m flake8 --config "$REPO/setup.cfg" .
fi
A=$?

# -----------------------------------------------------------------------------
DEBUG="$(grep --recursive --line-number \
    --exclude-dir='docs' \
    --regexp='\b\(el\)\?if [01]\(:\| and \| or \)' \
    --regexp='\band 0\b' \
    --regexp='\bor 1\b' \
    --regexp='[[:digit:]]/0\b' \
    --regexp='\bexit()' \
    --regexp='\bprint(' \
    --regexp='\._dump(' \
    . \
)"

if [[ "$DEBUG" ]]; then
    DEBUG="$( printf %s "$DEBUG " | sed -e 's/   */\n    /' )"
    printf '### Debug Remains:\n%s\n' "$DEBUG"
    B=1
fi

# -----------------------------------------------------------------------------
if [[ "$A" > 0 || "$B" > 0 ]]; then
    exit 1
fi
